// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8PJRQcC6rP7NibfaQAqe45PV_BXz1A0M',
    appId: '1:89107806854:web:3205710d1ab664af6def07',
    messagingSenderId: '89107806854',
    projectId: 'fir-dersleri-2e71b',
    authDomain: 'fir-dersleri-2e71b.firebaseapp.com',
    storageBucket: 'fir-dersleri-2e71b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC21-i5KxWCDNzMICmyCZZMtmgF1MUp7M',
    appId: '1:89107806854:android:5bb112e61aaf49136def07',
    messagingSenderId: '89107806854',
    projectId: 'fir-dersleri-2e71b',
    storageBucket: 'fir-dersleri-2e71b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUlcmKNQI53te1tmsC7ldoU0eVeI-j2UA',
    appId: '1:89107806854:ios:61dbe59ca853e8bd6def07',
    messagingSenderId: '89107806854',
    projectId: 'fir-dersleri-2e71b',
    storageBucket: 'fir-dersleri-2e71b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUlcmKNQI53te1tmsC7ldoU0eVeI-j2UA',
    appId: '1:89107806854:ios:61dbe59ca853e8bd6def07',
    messagingSenderId: '89107806854',
    projectId: 'fir-dersleri-2e71b',
    storageBucket: 'fir-dersleri-2e71b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseapp',
  );
}
